<a href="https://colab.research.google.com/github/AnshitaGarg/AirlinesDataAnalysis/blob/main/exp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [4]:
print("### Creating Tensors ###")
# 1D, 2D, 3D tensors
tensor_1d = torch.tensor([1, 2, 3])
tensor_2d = torch.tensor([[1, 2], [3, 4]])
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


### Creating Tensors ###


In [5]:
np_1d = np.array([1, 2, 3])
np_2d = np.array([[1, 2], [3, 4]])
np_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [6]:
print(f"1D PyTorch: {tensor_1d}")
print(f"2D PyTorch: \n{tensor_2d}")
print(f"3D PyTorch: \n{tensor_3d}")

print(f"1D NumPy: {np_1d}")
print(f"2D NumPy: \n{np_2d}")
print(f"3D NumPy: \n{np_3d}")


1D PyTorch: tensor([1, 2, 3])
2D PyTorch: 
tensor([[1, 2],
        [3, 4]])
3D PyTorch: 
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
1D NumPy: [1 2 3]
2D NumPy: 
[[1 2]
 [3 4]]
3D NumPy: 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
print("\n### Basic Operations ###")
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])


### Basic Operations ###


In [8]:
print(f"Addition: {a + b}")
print(f"Subtraction: {a - b}")
print(f"Multiplication: {a * b}")
print(f"Division: {a / b}")


Addition: tensor([5., 7., 9.])
Subtraction: tensor([-3., -3., -3.])
Multiplication: tensor([ 4., 10., 18.])
Division: tensor([0.2500, 0.4000, 0.5000])


In [9]:
print("\n### Dot Product and Matrix Multiplication ###")
vec1 = torch.tensor([1, 2, 3])
vec2 = torch.tensor([4, 5, 6])
dot = torch.dot(vec1, vec2)


### Dot Product and Matrix Multiplication ###


In [10]:
print(f"Dot Product: {dot}")

Dot Product: 32


In [11]:
mat1 = torch.tensor([[1, 2], [3, 4]])
mat2 = torch.tensor([[5, 6], [7, 8]])
matmul = torch.matmul(mat1, mat2)
print(f"Matrix Multiplication:\n{matmul}")

Matrix Multiplication:
tensor([[19, 22],
        [43, 50]])


In [12]:
print("\n### Indexing and Slicing ###")
tensor = torch.tensor([[10, 20, 30], [40, 50, 60]])


### Indexing and Slicing ###


In [13]:
print(f"Original Tensor:\n{tensor}")
print(f"Element [1,2]: {tensor[1,2]}")
print(f"First Row: {tensor[0]}")
print(f"Boolean Masking > 30: {tensor[tensor > 30]}")
print(f"Extracted Subtensor: {tensor[:, 1:]}")

Original Tensor:
tensor([[10, 20, 30],
        [40, 50, 60]])
Element [1,2]: 60
First Row: tensor([10, 20, 30])
Boolean Masking > 30: tensor([40, 50, 60])
Extracted Subtensor: tensor([[20, 30],
        [50, 60]])


In [14]:
print("\n### Reshaping Tensors ###")
x = torch.arange(6)
print(f"Original x: {x}")
print(f"x.view(2, 3):\n{x.view(2, 3)}")
print(f"x.reshape(2, 3):\n{x.reshape(2, 3)}")


### Reshaping Tensors ###
Original x: tensor([0, 1, 2, 3, 4, 5])
x.view(2, 3):
tensor([[0, 1, 2],
        [3, 4, 5]])
x.reshape(2, 3):
tensor([[0, 1, 2],
        [3, 4, 5]])


In [15]:
y = torch.tensor([[1, 2], [3, 4]])
print(f"Unsqueeze y (add dim 0):\n{y.unsqueeze(0)}")
print(f"Squeeze y (remove dim):\n{y.unsqueeze(0).squeeze()}")

Unsqueeze y (add dim 0):
tensor([[[1, 2],
         [3, 4]]])
Squeeze y (remove dim):
tensor([[1, 2],
        [3, 4]])


In [16]:
# NumPy Comparison
np_x = np.arange(6)
print(f"NumPy Reshape:\n{np_x.reshape(2, 3)}")

print("\n### Broadcasting ###")
a = torch.tensor([[1], [2], [3]])
b = torch.tensor([10, 20, 30])
print(f"a shape: {a.shape}, b shape: {b.shape}")
print(f"Broadcasted Addition:\n{a + b}")

print("\n### In-place vs Out-of-place Operations ###")
t = torch.tensor([1.0, 2.0, 3.0])
print(f"Original t: {t}")


NumPy Reshape:
[[0 1 2]
 [3 4 5]]

### Broadcasting ###
a shape: torch.Size([3, 1]), b shape: torch.Size([3])
Broadcasted Addition:
tensor([[11, 21, 31],
        [12, 22, 32],
        [13, 23, 33]])

### In-place vs Out-of-place Operations ###
Original t: tensor([1., 2., 3.])


In [17]:
# Out-of-place
t_add = t + 2
print(f"t + 2 (Out-of-place): {t_add}")
print(f"t after out-of-place: {t}")

# In-place
t.add_(2)
print(f"t after add_ (In-place): {t}")

t + 2 (Out-of-place): tensor([3., 4., 5.])
t after out-of-place: tensor([1., 2., 3.])
t after add_ (In-place): tensor([3., 4., 5.])
